//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner.Controls.ContextMenu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextMenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextMenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.Controls.ContextMenu.ContextMenuResources", typeof(ContextMenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_32 {
            get {
                object obj = ResourceManager.GetObject("filter_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sort_alphabetical_32 {
            get {
                object obj = ResourceManager.GetObject("sort_alphabetical_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Object List.
        /// </summary>
        internal static string Str_ModeFlat {
            get {
                return ResourceManager.GetString("Str_ModeFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        internal static string Str_ModeHierarchy {
            get {
                return ResourceManager.GetString("Str_ModeHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string Str_ModeLayer {
            get {
                return ResourceManager.GetString("Str_ModeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Str_ModeMaterial {
            get {
                return ResourceManager.GetString("Str_ModeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Set.
        /// </summary>
        internal static string Str_ModeSelSet {
            get {
                return ResourceManager.GetString("Str_ModeSelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Window.
        /// </summary>
        internal static string Str_WindowSingle {
            get {
                return ResourceManager.GetString("Str_WindowSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Horizontally.
        /// </summary>
        internal static string Str_WindowSplitHor {
            get {
                return ResourceManager.GetString("Str_WindowSplitHor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Vertically.
        /// </summary>
        internal static string Str_WindowSplitVer {
            get {
                return ResourceManager.GetString("Str_WindowSplitVer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_32 {
            get {
                object obj = ResourceManager.GetObject("window_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_hor_32 {
            get {
                object obj = ResourceManager.GetObject("window_hor_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_split_hor {
            get {
                object obj = ResourceManager.GetObject("window_split_hor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_split_ver {
            get {
                object obj = ResourceManager.GetObject("window_split_ver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_ver_32 {
            get {
                object obj = ResourceManager.GetObject("window_ver_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
