//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutlinerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutlinerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.OutlinerResources", typeof(OutlinerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_button {
            get {
                object obj = ResourceManager.GetObject("add_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_button_disabled {
            get {
                object obj = ResourceManager.GetObject("add_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap boxmode_button {
            get {
                object obj = ResourceManager.GetObject("boxmode_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap boxmode_button_disabled {
            get {
                object obj = ResourceManager.GetObject("boxmode_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Layer.
        /// </summary>
        internal static string Command_AddToLayer {
            get {
                return ResourceManager.GetString("Command_AddToLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string Command_Freeze {
            get {
                return ResourceManager.GetString("Command_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Command_Hide {
            get {
                return ResourceManager.GetString("Command_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Command_Select {
            get {
                return ResourceManager.GetString("Command_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change BoxMode.
        /// </summary>
        internal static string Command_SetBoxMode {
            get {
                return ResourceManager.GetString("Command_SetBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change WireColor.
        /// </summary>
        internal static string Command_SetWireColor {
            get {
                return ResourceManager.GetString("Command_SetWireColor", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap freeze_button {
            get {
                object obj = ResourceManager.GetObject("freeze_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap freeze_button_disabled {
            get {
                object obj = ResourceManager.GetObject("freeze_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hide_button {
            get {
                object obj = ResourceManager.GetObject("hide_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hide_button_disabled {
            get {
                object obj = ResourceManager.GetObject("hide_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
