//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutlinerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutlinerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.OutlinerResources", typeof(OutlinerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Outliner.
        /// </summary>
        internal static string Action_ToggleOutliner {
            get {
                return ResourceManager.GetString("Action_ToggleOutliner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - All objects -.
        /// </summary>
        internal static string AllObjectsSelSet {
            get {
                return ResourceManager.GetString("AllObjectsSelSet", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap button_add {
            get {
                object obj = ResourceManager.GetObject("button_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_boxmode {
            get {
                object obj = ResourceManager.GetObject("button_boxmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_freeze {
            get {
                object obj = ResourceManager.GetObject("button_freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_hide {
            get {
                object obj = ResourceManager.GetObject("button_hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_layer {
            get {
                object obj = ResourceManager.GetObject("button_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_remove {
            get {
                object obj = ResourceManager.GetObject("button_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_render {
            get {
                object obj = ResourceManager.GetObject("button_render", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap color_small {
            get {
                object obj = ResourceManager.GetObject("color_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Layer.
        /// </summary>
        internal static string Command_AddToLayer {
            get {
                return ResourceManager.GetString("Command_AddToLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string Command_Freeze {
            get {
                return ResourceManager.GetString("Command_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group nodes.
        /// </summary>
        internal static string Command_Group {
            get {
                return ResourceManager.GetString("Command_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Command_Hide {
            get {
                return ResourceManager.GetString("Command_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Command_Link {
            get {
                return ResourceManager.GetString("Command_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Layer.
        /// </summary>
        internal static string Command_LinkLayer {
            get {
                return ResourceManager.GetString("Command_LinkLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Selection-set.
        /// </summary>
        internal static string Command_ModifySelSet {
            get {
                return ResourceManager.GetString("Command_ModifySelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Command_Rename {
            get {
                return ResourceManager.GetString("Command_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Command_Select {
            get {
                return ResourceManager.GetString("Command_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change BoxMode.
        /// </summary>
        internal static string Command_SetBoxMode {
            get {
                return ResourceManager.GetString("Command_SetBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color tag.
        /// </summary>
        internal static string Command_SetColorTag {
            get {
                return ResourceManager.GetString("Command_SetColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Current Layer.
        /// </summary>
        internal static string Command_SetCurrentLayer {
            get {
                return ResourceManager.GetString("Command_SetCurrentLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change node property.
        /// </summary>
        internal static string Command_SetProperty {
            get {
                return ResourceManager.GetString("Command_SetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Renderable.
        /// </summary>
        internal static string Command_SetRenderable {
            get {
                return ResourceManager.GetString("Command_SetRenderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change WireColor.
        /// </summary>
        internal static string Command_SetWireColor {
            get {
                return ResourceManager.GetString("Command_SetWireColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Light.
        /// </summary>
        internal static string Command_ToggleLight {
            get {
                return ResourceManager.GetString("Command_ToggleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup nodes.
        /// </summary>
        internal static string Command_Ungroup {
            get {
                return ResourceManager.GetString("Command_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        internal static string Command_Unlink {
            get {
                return ResourceManager.GetString("Command_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink Layer.
        /// </summary>
        internal static string Command_UnlinkLayer {
            get {
                return ResourceManager.GetString("Command_UnlinkLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide selection.
        /// </summary>
        internal static string Context_Hide {
            get {
                return ResourceManager.GetString("Context_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide selection.
        /// </summary>
        internal static string Context_Unhide {
            get {
                return ResourceManager.GetString("Context_Unhide", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete_small {
            get {
                object obj = ResourceManager.GetObject("delete_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected nodes to layer.
        /// </summary>
        internal static string Tooltip_Add_Layer {
            get {
                return ResourceManager.GetString("Tooltip_Add_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected nodes to selection-set.
        /// </summary>
        internal static string Tooltip_Add_SelSet {
            get {
                return ResourceManager.GetString("Tooltip_Add_SelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle boxmode.
        /// </summary>
        internal static string Tooltip_BoxMode {
            get {
                return ResourceManager.GetString("Tooltip_BoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (overridden by parent/layer).
        /// </summary>
        internal static string Tooltip_ByLayer {
            get {
                return ResourceManager.GetString("Tooltip_ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse node.
        /// </summary>
        internal static string Tooltip_Collapse {
            get {
                return ResourceManager.GetString("Tooltip_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Tag: .
        /// </summary>
        internal static string Tooltip_ColorTag {
            get {
                return ResourceManager.GetString("Tooltip_ColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand node
        ///Use {0} to expand entire hierarchy..
        /// </summary>
        internal static string Tooltip_Expand {
            get {
                return ResourceManager.GetString("Tooltip_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string Tooltip_Freeze {
            get {
                return ResourceManager.GetString("Tooltip_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Tooltip_Hide {
            get {
                return ResourceManager.GetString("Tooltip_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inherited from layer).
        /// </summary>
        internal static string Tooltip_Inherited {
            get {
                return ResourceManager.GetString("Tooltip_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected nodes from selection-set.
        /// </summary>
        internal static string Tooltip_Remove_SelSet {
            get {
                return ResourceManager.GetString("Tooltip_Remove_SelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle renderable.
        /// </summary>
        internal static string Tooltip_Renderable {
            get {
                return ResourceManager.GetString("Tooltip_Renderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set camera for active viewport.
        /// </summary>
        internal static string Tooltip_SetCamera {
            get {
                return ResourceManager.GetString("Tooltip_SetCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set current layer.
        /// </summary>
        internal static string Tooltip_SetCurrentLayer {
            get {
                return ResourceManager.GetString("Tooltip_SetCurrentLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle light on/off.
        /// </summary>
        internal static string Tooltip_ToggleLight {
            get {
                return ResourceManager.GetString("Tooltip_ToggleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze.
        /// </summary>
        internal static string Tooltip_Unfreeze {
            get {
                return ResourceManager.GetString("Tooltip_Unfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide.
        /// </summary>
        internal static string Tooltip_Unhide {
            get {
                return ResourceManager.GetString("Tooltip_Unhide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change wirecolor.
        /// </summary>
        internal static string Tooltip_WireColor {
            get {
                return ResourceManager.GetString("Tooltip_WireColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this node cannot be edited..
        /// </summary>
        internal static string Warning_CannotEditName {
            get {
                return ResourceManager.GetString("Warning_CannotEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit name.
        /// </summary>
        internal static string Warning_CannotEditNameTitle {
            get {
                return ResourceManager.GetString("Warning_CannotEditNameTitle", resourceCulture);
            }
        }
    }
}
