//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutlinerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutlinerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.OutlinerResources", typeof(OutlinerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outliner 3.
        /// </summary>
        internal static string Action_Category {
            get {
                return ResourceManager.GetString("Action_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on selection.
        /// </summary>
        internal static string Action_FocusOnSelection {
            get {
                return ResourceManager.GetString("Action_FocusOnSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Outliner.
        /// </summary>
        internal static string Action_ToggleOutliner {
            get {
                return ResourceManager.GetString("Action_ToggleOutliner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Space.
        /// </summary>
        internal static string Button_EmptySpace {
            get {
                return ResourceManager.GetString("Button_EmptySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Button.
        /// </summary>
        internal static string Button_ExpandButton {
            get {
                return ResourceManager.GetString("Button_ExpandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeNode Indent.
        /// </summary>
        internal static string Button_TreeNodeIndent {
            get {
                return ResourceManager.GetString("Button_TreeNodeIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name.
        /// </summary>
        internal static string Button_TreeNodeText {
            get {
                return ResourceManager.GetString("Button_TreeNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to new container.
        /// </summary>
        internal static string Command_AddToNewContainer {
            get {
                return ResourceManager.GetString("Command_AddToNewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string Command_Freeze {
            get {
                return ResourceManager.GetString("Command_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group nodes.
        /// </summary>
        internal static string Command_Group {
            get {
                return ResourceManager.GetString("Command_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Command_Hide {
            get {
                return ResourceManager.GetString("Command_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Command_Link {
            get {
                return ResourceManager.GetString("Command_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Layer.
        /// </summary>
        internal static string Command_LinkLayer {
            get {
                return ResourceManager.GetString("Command_LinkLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Command_Rename {
            get {
                return ResourceManager.GetString("Command_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Command_Select {
            get {
                return ResourceManager.GetString("Command_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change BoxMode.
        /// </summary>
        internal static string Command_SetBoxMode {
            get {
                return ResourceManager.GetString("Command_SetBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color tag.
        /// </summary>
        internal static string Command_SetColorTag {
            get {
                return ResourceManager.GetString("Command_SetColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change node property.
        /// </summary>
        internal static string Command_SetProperty {
            get {
                return ResourceManager.GetString("Command_SetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Renderable.
        /// </summary>
        internal static string Command_SetRenderable {
            get {
                return ResourceManager.GetString("Command_SetRenderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change WireColor.
        /// </summary>
        internal static string Command_SetWireColor {
            get {
                return ResourceManager.GetString("Command_SetWireColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Light.
        /// </summary>
        internal static string Command_ToggleLight {
            get {
                return ResourceManager.GetString("Command_ToggleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup Nodes.
        /// </summary>
        internal static string Command_Ungroup {
            get {
                return ResourceManager.GetString("Command_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        internal static string Command_Unlink {
            get {
                return ResourceManager.GetString("Command_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink Layer.
        /// </summary>
        internal static string Command_UnlinkLayer {
            get {
                return ResourceManager.GetString("Command_UnlinkLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap default_preset_16 {
            get {
                object obj = ResourceManager.GetObject("default_preset_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap default_preset_24 {
            get {
                object obj = ResourceManager.GetObject("default_preset_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinator.
        /// </summary>
        internal static string Filter_Combinator {
            get {
                return ResourceManager.GetString("Filter_Combinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible Nodes.
        /// </summary>
        internal static string Filter_InvisibleNodes {
            get {
                return ResourceManager.GetString("Filter_InvisibleNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxscript Filter.
        /// </summary>
        internal static string Filter_Maxscript {
            get {
                return ResourceManager.GetString("Filter_Maxscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Filter_Name {
            get {
                return ResourceManager.GetString("Filter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Property.
        /// </summary>
        internal static string Filter_NodeProperty {
            get {
                return ResourceManager.GetString("Filter_NodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outliner.
        /// </summary>
        internal static string Outliner_WindowTitle {
            get {
                return ResourceManager.GetString("Outliner_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context-Menu.
        /// </summary>
        internal static string Preset_ContextMenu {
            get {
                return ResourceManager.GetString("Preset_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Presets.
        /// </summary>
        internal static string Preset_Custom {
            get {
                return ResourceManager.GetString("Preset_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Presets.
        /// </summary>
        internal static string Preset_Default {
            get {
                return ResourceManager.GetString("Preset_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Preset_Filter {
            get {
                return ResourceManager.GetString("Preset_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Preset_Layout {
            get {
                return ResourceManager.GetString("Preset_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorter.
        /// </summary>
        internal static string Preset_Sorter {
            get {
                return ResourceManager.GetString("Preset_Sorter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_alphabetical_16_dark {
            get {
                object obj = ResourceManager.GetObject("sort_alphabetical_16_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_alphabetical_24_dark {
            get {
                object obj = ResourceManager.GetObject("sort_alphabetical_24_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_alphabetical_32_dark {
            get {
                object obj = ResourceManager.GetObject("sort_alphabetical_32_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_default_16 {
            get {
                object obj = ResourceManager.GetObject("sort_default_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_default_24 {
            get {
                object obj = ResourceManager.GetObject("sort_default_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string Sorter_Alphabetical {
            get {
                return ResourceManager.GetString("Sorter_Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Property.
        /// </summary>
        internal static string Sorter_NodeProperty {
            get {
                return ResourceManager.GetString("Sorter_NodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string Str_INode {
            get {
                return ResourceManager.GetString("Str_INode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse node.
        /// </summary>
        internal static string Tooltip_Collapse {
            get {
                return ResourceManager.GetString("Tooltip_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand node
        ///Use {0} to expand entire hierarchy..
        /// </summary>
        internal static string Tooltip_Expand {
            get {
                return ResourceManager.GetString("Tooltip_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inherited from layer).
        /// </summary>
        internal static string Tooltip_Inherited {
            get {
                return ResourceManager.GetString("Tooltip_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this node cannot be edited..
        /// </summary>
        internal static string Warning_CannotEditName {
            get {
                return ResourceManager.GetString("Warning_CannotEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit name.
        /// </summary>
        internal static string Warning_CannotEditNameTitle {
            get {
                return ResourceManager.GetString("Warning_CannotEditNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?
        ///This action cannot be undone..
        /// </summary>
        internal static string Warning_DeleteConfig {
            get {
                return ResourceManager.GetString("Warning_DeleteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete configuration?.
        /// </summary>
        internal static string Warning_DeleteConfigTitle {
            get {
                return ResourceManager.GetString("Warning_DeleteConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the Outliner settings failed. This could mean that your Outliner installation is corrupt, and it will have to be reinstalled.
        ///
        ///To try to reload the settings manually, use Outliner.ReloadSettings()
        ///For more details on the error, see Outliner.SettingsLoadException.ToString().
        /// </summary>
        internal static string Warning_SettingsNotLoaded {
            get {
                return ResourceManager.GetString("Warning_SettingsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings.
        /// </summary>
        internal static string Warning_SettingsNotLoaded_Title {
            get {
                return ResourceManager.GetString("Warning_SettingsNotLoaded_Title", resourceCulture);
            }
        }
    }
}
