//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner.Controls.ContextMenu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextMenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextMenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.Controls.ContextMenu.ContextMenuResources", typeof(ContextMenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap childnodes_16 {
            get {
                object obj = ResourceManager.GetObject("childnodes_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selection To.
        /// </summary>
        internal static string Context_AddSelectionTo {
            get {
                return ResourceManager.GetString("Context_AddSelectionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Container.
        /// </summary>
        internal static string Context_AddToNewContainer {
            get {
                return ResourceManager.GetString("Context_AddToNewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string Context_AddToNewGroup {
            get {
                return ResourceManager.GetString("Context_AddToNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layer.
        /// </summary>
        internal static string Context_AddToNewLayer {
            get {
                return ResourceManager.GetString("Context_AddToNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Selection-Set.
        /// </summary>
        internal static string Context_AddToSelSet {
            get {
                return ResourceManager.GetString("Context_AddToSelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply atmospherics.
        /// </summary>
        internal static string Context_ApplyAtmospherics {
            get {
                return ResourceManager.GetString("Context_ApplyAtmospherics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backface cull.
        /// </summary>
        internal static string Context_BackfaceCull {
            get {
                return ResourceManager.GetString("Context_BackfaceCull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box mode.
        /// </summary>
        internal static string Context_Boxmode {
            get {
                return ResourceManager.GetString("Context_Boxmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Layer.
        /// </summary>
        internal static string Context_ByLayer {
            get {
                return ResourceManager.GetString("Context_ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast shadows.
        /// </summary>
        internal static string Context_CastShadows {
            get {
                return ResourceManager.GetString("Context_CastShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Context_ClearFilter {
            get {
                return ResourceManager.GetString("Context_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Context_Delete {
            get {
                return ResourceManager.GetString("Context_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all nodes by layer.
        /// </summary>
        internal static string Context_DisplayAllByLayer {
            get {
                return ResourceManager.GetString("Context_DisplayAllByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display - Bounding box.
        /// </summary>
        internal static string Context_DisplayBoundingBox {
            get {
                return ResourceManager.GetString("Context_DisplayBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        internal static string Context_DisplaySettings {
            get {
                return ResourceManager.GetString("Context_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display - Shaded.
        /// </summary>
        internal static string Context_DisplayShaded {
            get {
                return ResourceManager.GetString("Context_DisplayShaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display - Viewport.
        /// </summary>
        internal static string Context_DisplayViewport {
            get {
                return ResourceManager.GetString("Context_DisplayViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display - Wireframe.
        /// </summary>
        internal static string Context_DisplayWireframe {
            get {
                return ResourceManager.GetString("Context_DisplayWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Context-Menus....
        /// </summary>
        internal static string Context_EditContextMenus {
            get {
                return ResourceManager.GetString("Context_EditContextMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filters....
        /// </summary>
        internal static string Context_EditFilters {
            get {
                return ResourceManager.GetString("Context_EditFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layouts....
        /// </summary>
        internal static string Context_EditLayouts {
            get {
                return ResourceManager.GetString("Context_EditLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Presets....
        /// </summary>
        internal static string Context_EditPresets {
            get {
                return ResourceManager.GetString("Context_EditPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sorters....
        /// </summary>
        internal static string Context_EditSorters {
            get {
                return ResourceManager.GetString("Context_EditSorters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Context_Filters {
            get {
                return ResourceManager.GetString("Context_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Selection.
        /// </summary>
        internal static string Context_FreezeSelection {
            get {
                return ResourceManager.GetString("Context_FreezeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen in gray.
        /// </summary>
        internal static string Context_FrozenInGray {
            get {
                return ResourceManager.GetString("Context_FrozenInGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Selection.
        /// </summary>
        internal static string Context_HideSelection {
            get {
                return ResourceManager.GetString("Context_HideSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit visibility.
        /// </summary>
        internal static string Context_InheritVisibility {
            get {
                return ResourceManager.GetString("Context_InheritVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string Context_InvertFilter {
            get {
                return ResourceManager.GetString("Context_InvertFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Context_Layout {
            get {
                return ResourceManager.GetString("Context_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Context_ObjectProperties {
            get {
                return ResourceManager.GetString("Context_ObjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Context_Options {
            get {
                return ResourceManager.GetString("Context_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string Context_Preset {
            get {
                return ResourceManager.GetString("Context_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to camera.
        /// </summary>
        internal static string Context_PrimaryVisibility {
            get {
                return ResourceManager.GetString("Context_PrimaryVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive shadows.
        /// </summary>
        internal static string Context_ReceiveShadows {
            get {
                return ResourceManager.GetString("Context_ReceiveShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Context_Rename {
            get {
                return ResourceManager.GetString("Context_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderable.
        /// </summary>
        internal static string Context_Renderable {
            get {
                return ResourceManager.GetString("Context_Renderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render all nodes by layer.
        /// </summary>
        internal static string Context_RenderAllByLayer {
            get {
                return ResourceManager.GetString("Context_RenderAllByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render occluded.
        /// </summary>
        internal static string Context_RenderOccluded {
            get {
                return ResourceManager.GetString("Context_RenderOccluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Settings.
        /// </summary>
        internal static string Context_RenderSettings {
            get {
                return ResourceManager.GetString("Context_RenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to reflection/refraction.
        /// </summary>
        internal static string Context_SecondaryVisibility {
            get {
                return ResourceManager.GetString("Context_SecondaryVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See-through.
        /// </summary>
        internal static string Context_SeeThrough {
            get {
                return ResourceManager.GetString("Context_SeeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Childnodes.
        /// </summary>
        internal static string Context_SelectChildnodes {
            get {
                return ResourceManager.GetString("Context_SelectChildnodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string Context_Sorting {
            get {
                return ResourceManager.GetString("Context_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show trajectory.
        /// </summary>
        internal static string Context_Trajectory {
            get {
                return ResourceManager.GetString("Context_Trajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze Selection.
        /// </summary>
        internal static string Context_UnfreezeSelection {
            get {
                return ResourceManager.GetString("Context_UnfreezeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide Selection.
        /// </summary>
        internal static string Context_UnhideSelection {
            get {
                return ResourceManager.GetString("Context_UnhideSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        internal static string Context_WindowNew {
            get {
                return ResourceManager.GetString("Context_WindowNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Window.
        /// </summary>
        internal static string Context_WindowSingle {
            get {
                return ResourceManager.GetString("Context_WindowSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Horizontally.
        /// </summary>
        internal static string Context_WindowSplitHor {
            get {
                return ResourceManager.GetString("Context_WindowSplitHor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Vertically.
        /// </summary>
        internal static string Context_WindowSplitVer {
            get {
                return ResourceManager.GetString("Context_WindowSplitVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter_16 {
            get {
                object obj = ResourceManager.GetObject("filter_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter_24 {
            get {
                object obj = ResourceManager.GetObject("filter_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freeze {
            get {
                object obj = ResourceManager.GetObject("freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide {
            get {
                object obj = ResourceManager.GetObject("hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_16 {
            get {
                object obj = ResourceManager.GetObject("layer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_container_16 {
            get {
                object obj = ResourceManager.GetObject("new_container_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_group_16 {
            get {
                object obj = ResourceManager.GetObject("new_group_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_layer_16 {
            get {
                object obj = ResourceManager.GetObject("new_layer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_selectionset_16 {
            get {
                object obj = ResourceManager.GetObject("new_selectionset_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options_24 {
            get {
                object obj = ResourceManager.GetObject("options_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap properties {
            get {
                object obj = ResourceManager.GetObject("properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Item.
        /// </summary>
        internal static string Str_ActionMenuItemModel {
            get {
                return ResourceManager.GetString("Str_ActionMenuItemModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &quot;{0}&quot; not found!.
        /// </summary>
        internal static string Str_ActionNotFound {
            get {
                return ResourceManager.GetString("Str_ActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Add To Layer Items -.
        /// </summary>
        internal static string Str_AddToLayerItems {
            get {
                return ResourceManager.GetString("Str_AddToLayerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu warning.
        /// </summary>
        internal static string Str_ContextMenuWarningTitle {
            get {
                return ResourceManager.GetString("Str_ContextMenuWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Hide / Freeze Items -.
        /// </summary>
        internal static string Str_HideFreezeItems {
            get {
                return ResourceManager.GetString("Str_HideFreezeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Include Model File -.
        /// </summary>
        internal static string Str_IncludeContextMenuModel {
            get {
                return ResourceManager.GetString("Str_IncludeContextMenuModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxscript Item.
        /// </summary>
        internal static string Str_MxsMenuItemModel {
            get {
                return ResourceManager.GetString("Str_MxsMenuItemModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Property Item.
        /// </summary>
        internal static string Str_NodePropertyMenuItemModel {
            get {
                return ResourceManager.GetString("Str_NodePropertyMenuItemModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Separator --.
        /// </summary>
        internal static string Str_SeparatorMenuItemModel {
            get {
                return ResourceManager.GetString("Str_SeparatorMenuItemModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_24 {
            get {
                object obj = ResourceManager.GetObject("window_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_hor_24 {
            get {
                object obj = ResourceManager.GetObject("window_hor_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_new_16 {
            get {
                object obj = ResourceManager.GetObject("window_new_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_split_hor {
            get {
                object obj = ResourceManager.GetObject("window_split_hor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_split_ver {
            get {
                object obj = ResourceManager.GetObject("window_split_ver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_ver_24 {
            get {
                object obj = ResourceManager.GetObject("window_ver_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
