//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner.Controls.ContextMenu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextMenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextMenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.Controls.ContextMenu.ContextMenuResources", typeof(ContextMenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_16 {
            get {
                object obj = ResourceManager.GetObject("filter_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_24 {
            get {
                object obj = ResourceManager.GetObject("filter_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap freeze {
            get {
                object obj = ResourceManager.GetObject("freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hide {
            get {
                object obj = ResourceManager.GetObject("hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer {
            get {
                object obj = ResourceManager.GetObject("layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newcontainer {
            get {
                object obj = ResourceManager.GetObject("newcontainer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newgroup {
            get {
                object obj = ResourceManager.GetObject("newgroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newlayer {
            get {
                object obj = ResourceManager.GetObject("newlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap options_24 {
            get {
                object obj = ResourceManager.GetObject("options_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap properties {
            get {
                object obj = ResourceManager.GetObject("properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &quot;{0}&quot; not found!.
        /// </summary>
        internal static string Str_ActionNotFound {
            get {
                return ResourceManager.GetString("Str_ActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selection To.
        /// </summary>
        internal static string Str_AddSelectionTo {
            get {
                return ResourceManager.GetString("Str_AddSelectionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Container.
        /// </summary>
        internal static string Str_AddToNewContainer {
            get {
                return ResourceManager.GetString("Str_AddToNewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string Str_AddToNewGroup {
            get {
                return ResourceManager.GetString("Str_AddToNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layer.
        /// </summary>
        internal static string Str_AddToNewLayer {
            get {
                return ResourceManager.GetString("Str_AddToNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Selection-Set.
        /// </summary>
        internal static string Str_AddToSelSet {
            get {
                return ResourceManager.GetString("Str_AddToSelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply atmospherics.
        /// </summary>
        internal static string Str_ApplyAtmospherics {
            get {
                return ResourceManager.GetString("Str_ApplyAtmospherics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backface cull.
        /// </summary>
        internal static string Str_BackfaceCull {
            get {
                return ResourceManager.GetString("Str_BackfaceCull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box mode.
        /// </summary>
        internal static string Str_Boxmode {
            get {
                return ResourceManager.GetString("Str_Boxmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Layer.
        /// </summary>
        internal static string Str_ByLayer {
            get {
                return ResourceManager.GetString("Str_ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast shadows.
        /// </summary>
        internal static string Str_CastShadows {
            get {
                return ResourceManager.GetString("Str_CastShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Str_ClearFilter {
            get {
                return ResourceManager.GetString("Str_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu warning.
        /// </summary>
        internal static string Str_ContextMenuWarningTitle {
            get {
                return ResourceManager.GetString("Str_ContextMenuWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Str_Delete {
            get {
                return ResourceManager.GetString("Str_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        internal static string Str_DisplaySettings {
            get {
                return ResourceManager.GetString("Str_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Presets.
        /// </summary>
        internal static string Str_EditPresets {
            get {
                return ResourceManager.GetString("Str_EditPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Selection.
        /// </summary>
        internal static string Str_FreezeSelection {
            get {
                return ResourceManager.GetString("Str_FreezeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen in gray.
        /// </summary>
        internal static string Str_FrozenInGray {
            get {
                return ResourceManager.GetString("Str_FrozenInGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Selection.
        /// </summary>
        internal static string Str_HideSelection {
            get {
                return ResourceManager.GetString("Str_HideSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit visibility.
        /// </summary>
        internal static string Str_InheritVisibility {
            get {
                return ResourceManager.GetString("Str_InheritVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string Str_InvertFilter {
            get {
                return ResourceManager.GetString("Str_InvertFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Object List.
        /// </summary>
        internal static string Str_ModeFlat {
            get {
                return ResourceManager.GetString("Str_ModeFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        internal static string Str_ModeHierarchy {
            get {
                return ResourceManager.GetString("Str_ModeHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string Str_ModeLayer {
            get {
                return ResourceManager.GetString("Str_ModeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Str_ModeMaterial {
            get {
                return ResourceManager.GetString("Str_ModeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Set.
        /// </summary>
        internal static string Str_ModeSelSet {
            get {
                return ResourceManager.GetString("Str_ModeSelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Str_ObjectProperties {
            get {
                return ResourceManager.GetString("Str_ObjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to camera.
        /// </summary>
        internal static string Str_PrimaryVisibility {
            get {
                return ResourceManager.GetString("Str_PrimaryVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive shadows.
        /// </summary>
        internal static string Str_ReceiveShadows {
            get {
                return ResourceManager.GetString("Str_ReceiveShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Str_Rename {
            get {
                return ResourceManager.GetString("Str_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderable.
        /// </summary>
        internal static string Str_Renderable {
            get {
                return ResourceManager.GetString("Str_Renderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render occluded.
        /// </summary>
        internal static string Str_RenderOccluded {
            get {
                return ResourceManager.GetString("Str_RenderOccluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Settings.
        /// </summary>
        internal static string Str_RenderSettings {
            get {
                return ResourceManager.GetString("Str_RenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Preset.
        /// </summary>
        internal static string Str_SavePreset {
            get {
                return ResourceManager.GetString("Str_SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to reflection/refraction.
        /// </summary>
        internal static string Str_SecondaryVisibility {
            get {
                return ResourceManager.GetString("Str_SecondaryVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See-through.
        /// </summary>
        internal static string Str_SeeThrough {
            get {
                return ResourceManager.GetString("Str_SeeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounding box.
        /// </summary>
        internal static string Str_ShowBoundingBox {
            get {
                return ResourceManager.GetString("Str_ShowBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in viewport.
        /// </summary>
        internal static string Str_ShowInViewport {
            get {
                return ResourceManager.GetString("Str_ShowInViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaded.
        /// </summary>
        internal static string Str_ShowShaded {
            get {
                return ResourceManager.GetString("Str_ShowShaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        internal static string Str_ShowWireframe {
            get {
                return ResourceManager.GetString("Str_ShowWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show trajectory.
        /// </summary>
        internal static string Str_Trajectory {
            get {
                return ResourceManager.GetString("Str_Trajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze Selection.
        /// </summary>
        internal static string Str_UnfreezeSelection {
            get {
                return ResourceManager.GetString("Str_UnfreezeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide Selection.
        /// </summary>
        internal static string Str_UnhideSelection {
            get {
                return ResourceManager.GetString("Str_UnhideSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        internal static string Str_WindowNew {
            get {
                return ResourceManager.GetString("Str_WindowNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Window.
        /// </summary>
        internal static string Str_WindowSingle {
            get {
                return ResourceManager.GetString("Str_WindowSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Horizontally.
        /// </summary>
        internal static string Str_WindowSplitHor {
            get {
                return ResourceManager.GetString("Str_WindowSplitHor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Vertically.
        /// </summary>
        internal static string Str_WindowSplitVer {
            get {
                return ResourceManager.GetString("Str_WindowSplitVer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_24 {
            get {
                object obj = ResourceManager.GetObject("window_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_hor_24 {
            get {
                object obj = ResourceManager.GetObject("window_hor_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_new_16 {
            get {
                object obj = ResourceManager.GetObject("window_new_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_split_hor {
            get {
                object obj = ResourceManager.GetObject("window_split_hor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_split_ver {
            get {
                object obj = ResourceManager.GetObject("window_split_ver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_ver_24 {
            get {
                object obj = ResourceManager.GetObject("window_ver_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
