//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJanssen.Outliner.Modes.XRef {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PJanssen.Outliner.Modes.XRef.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable xref scenes.
        /// </summary>
        internal static string Command_SetXrefSceneDisabled {
            get {
                return ResourceManager.GetString("Command_SetXrefSceneDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable xref scenes.
        /// </summary>
        internal static string Command_SetXrefSceneEnabled {
            get {
                return ResourceManager.GetString("Command_SetXrefSceneEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add XRef Scene.
        /// </summary>
        internal static string Context_AddXrefScene {
            get {
                return ResourceManager.GetString("Context_AddXrefScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string Context_Animation {
            get {
                return ResourceManager.GetString("Context_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Automatically.
        /// </summary>
        internal static string Context_AutoUpdate {
            get {
                return ResourceManager.GetString("Context_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Mode.
        /// </summary>
        internal static string Context_BoxMode {
            get {
                return ResourceManager.GetString("Context_BoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        internal static string Context_Cameras {
            get {
                return ResourceManager.GetString("Context_Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Context_Enabled {
            get {
                return ResourceManager.GetString("Context_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter XRef Scene.
        /// </summary>
        internal static string Context_Filter {
            get {
                return ResourceManager.GetString("Context_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpers.
        /// </summary>
        internal static string Context_Helpers {
            get {
                return ResourceManager.GetString("Context_Helpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Context_Hidden {
            get {
                return ResourceManager.GetString("Context_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights.
        /// </summary>
        internal static string Context_Lights {
            get {
                return ResourceManager.GetString("Context_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        internal static string Context_OpenContainingFolder {
            get {
                return ResourceManager.GetString("Context_OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In New Instance.
        /// </summary>
        internal static string Context_OpenInNewInstance {
            get {
                return ResourceManager.GetString("Context_OpenInNewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        internal static string Context_Shapes {
            get {
                return ResourceManager.GetString("Context_Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Context_Update {
            get {
                return ResourceManager.GetString("Context_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will open {0} new instances of 3dsMax.
        ///Are you sure you want to proceed?.
        /// </summary>
        internal static string Str_OpenManyInstances {
            get {
                return ResourceManager.GetString("Str_OpenManyInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new instance.
        /// </summary>
        internal static string Str_OpenManyInstancesTitle {
            get {
                return ResourceManager.GetString("Str_OpenManyInstancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set XRefSceneFlags Item.
        /// </summary>
        internal static string Str_SetXrefSceneFlagsItemModel {
            get {
                return ResourceManager.GetString("Str_SetXrefSceneFlagsItemModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRef Mode.
        /// </summary>
        internal static string Str_XrefMode {
            get {
                return ResourceManager.GetString("Str_XrefMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Auto-Update.
        /// </summary>
        internal static string Tooltip_AutoUpdate {
            get {
                return ResourceManager.GetString("Tooltip_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Tooltip_Disable {
            get {
                return ResourceManager.GetString("Tooltip_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Tooltip_Enable {
            get {
                return ResourceManager.GetString("Tooltip_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update xref record now.
        /// </summary>
        internal static string Tooltip_Update {
            get {
                return ResourceManager.GetString("Tooltip_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_16 {
            get {
                object obj = ResourceManager.GetObject("update_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xref_mode_16 {
            get {
                object obj = ResourceManager.GetObject("xref_mode_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xref_mode_24 {
            get {
                object obj = ResourceManager.GetObject("xref_mode_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
