//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJanssen.Outliner.TreeNodeButtons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PJanssen.Outliner.TreeNodeButtons.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_add {
            get {
                object obj = ResourceManager.GetObject("button_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_boxmode {
            get {
                object obj = ResourceManager.GetObject("button_boxmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_freeze {
            get {
                object obj = ResourceManager.GetObject("button_freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_hide {
            get {
                object obj = ResourceManager.GetObject("button_hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_layer {
            get {
                object obj = ResourceManager.GetObject("button_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_lock {
            get {
                object obj = ResourceManager.GetObject("button_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_lock_disabled {
            get {
                object obj = ResourceManager.GetObject("button_lock_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_remove {
            get {
                object obj = ResourceManager.GetObject("button_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_render {
            get {
                object obj = ResourceManager.GetObject("button_render", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To .
        /// </summary>
        internal static string Command_AddTo {
            get {
                return ResourceManager.GetString("Command_AddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock transforms.
        /// </summary>
        internal static string Command_LockTransforms {
            get {
                return ResourceManager.GetString("Command_LockTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From .
        /// </summary>
        internal static string Command_RemoveFrom {
            get {
                return ResourceManager.GetString("Command_RemoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock transforms.
        /// </summary>
        internal static string Command_UnlockTransforms {
            get {
                return ResourceManager.GetString("Command_UnlockTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Button.
        /// </summary>
        internal static string Str_AddButton {
            get {
                return ResourceManager.GetString("Str_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxmode Button.
        /// </summary>
        internal static string Str_BoxModeButton {
            get {
                return ResourceManager.GetString("Str_BoxModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Button.
        /// </summary>
        internal static string Str_FreezeButton {
            get {
                return ResourceManager.GetString("Str_FreezeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Button.
        /// </summary>
        internal static string Str_HideButton {
            get {
                return ResourceManager.GetString("Str_HideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Transforms Button.
        /// </summary>
        internal static string Str_LockTransformsButton {
            get {
                return ResourceManager.GetString("Str_LockTransformsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maya Style Indent.
        /// </summary>
        internal static string Str_MayaStyleIndent {
            get {
                return ResourceManager.GetString("Str_MayaStyleIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Icon.
        /// </summary>
        internal static string Str_NodeIcon {
            get {
                return ResourceManager.GetString("Str_NodeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Button.
        /// </summary>
        internal static string Str_RemoveButton {
            get {
                return ResourceManager.GetString("Str_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderable Button.
        /// </summary>
        internal static string Str_RenderableButton {
            get {
                return ResourceManager.GetString("Str_RenderableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirecolor Button.
        /// </summary>
        internal static string Str_WireColorButton {
            get {
                return ResourceManager.GetString("Str_WireColorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected nodes to .
        /// </summary>
        internal static string Tooltip_Add {
            get {
                return ResourceManager.GetString("Tooltip_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle boxmode.
        /// </summary>
        internal static string Tooltip_BoxMode {
            get {
                return ResourceManager.GetString("Tooltip_BoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (overridden by parent/layer).
        /// </summary>
        internal static string Tooltip_ByLayer {
            get {
                return ResourceManager.GetString("Tooltip_ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string Tooltip_Freeze {
            get {
                return ResourceManager.GetString("Tooltip_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Tooltip_Hide {
            get {
                return ResourceManager.GetString("Tooltip_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock transforms.
        /// </summary>
        internal static string Tooltip_LockTransforms {
            get {
                return ResourceManager.GetString("Tooltip_LockTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected nodes from .
        /// </summary>
        internal static string Tooltip_RemoveFrom {
            get {
                return ResourceManager.GetString("Tooltip_RemoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle renderable.
        /// </summary>
        internal static string Tooltip_Renderable {
            get {
                return ResourceManager.GetString("Tooltip_Renderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set camera for active viewport.
        /// </summary>
        internal static string Tooltip_SetCamera {
            get {
                return ResourceManager.GetString("Tooltip_SetCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set current layer.
        /// </summary>
        internal static string Tooltip_SetCurrentLayer {
            get {
                return ResourceManager.GetString("Tooltip_SetCurrentLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle light on/off.
        /// </summary>
        internal static string Tooltip_ToggleLight {
            get {
                return ResourceManager.GetString("Tooltip_ToggleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze.
        /// </summary>
        internal static string Tooltip_Unfreeze {
            get {
                return ResourceManager.GetString("Tooltip_Unfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide.
        /// </summary>
        internal static string Tooltip_Unhide {
            get {
                return ResourceManager.GetString("Tooltip_Unhide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock transforms.
        /// </summary>
        internal static string Tooltip_UnlockTransforms {
            get {
                return ResourceManager.GetString("Tooltip_UnlockTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change wirecolor.
        /// </summary>
        internal static string Tooltip_WireColor {
            get {
                return ResourceManager.GetString("Tooltip_WireColor", resourceCulture);
            }
        }
    }
}
