//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner.Filters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.Filters.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bones.
        /// </summary>
        internal static string Filter_Bones {
            get {
                return ResourceManager.GetString("Filter_Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        internal static string Filter_Cameras {
            get {
                return ResourceManager.GetString("Filter_Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen Nodes.
        /// </summary>
        internal static string Filter_Frozen {
            get {
                return ResourceManager.GetString("Filter_Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        internal static string Filter_Geometry {
            get {
                return ResourceManager.GetString("Filter_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpers.
        /// </summary>
        internal static string Filter_Helpers {
            get {
                return ResourceManager.GetString("Filter_Helpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Nodes.
        /// </summary>
        internal static string Filter_Hidden {
            get {
                return ResourceManager.GetString("Filter_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights.
        /// </summary>
        internal static string Filter_Lights {
            get {
                return ResourceManager.GetString("Filter_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurbs.
        /// </summary>
        internal static string Filter_Nurbs {
            get {
                return ResourceManager.GetString("Filter_Nurbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particles.
        /// </summary>
        internal static string Filter_Particles {
            get {
                return ResourceManager.GetString("Filter_Particles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        internal static string Filter_Shapes {
            get {
                return ResourceManager.GetString("Filter_Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacewarps.
        /// </summary>
        internal static string Filter_Spacewarps {
            get {
                return ResourceManager.GetString("Filter_Spacewarps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xrefs.
        /// </summary>
        internal static string Filter_Xref {
            get {
                return ResourceManager.GetString("Filter_Xref", resourceCulture);
            }
        }
    }
}
