//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner.Modes.MaterialMode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.Modes.MaterialMode.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign material.
        /// </summary>
        internal static string Command_AssignMaterial {
            get {
                return ResourceManager.GetString("Command_AssignMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Slate View.
        /// </summary>
        internal static string Context_CurrentSlate {
            get {
                return ResourceManager.GetString("Context_CurrentSlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Material In.
        /// </summary>
        internal static string Context_EditMaterial {
            get {
                return ResourceManager.GetString("Context_EditMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Editor Slot:.
        /// </summary>
        internal static string Context_MaterialSlot {
            get {
                return ResourceManager.GetString("Context_MaterialSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Slate View.
        /// </summary>
        internal static string Context_NewSlate {
            get {
                return ResourceManager.GetString("Context_NewSlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_material_16 {
            get {
                object obj = ResourceManager.GetObject("edit_material_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_editor_16 {
            get {
                object obj = ResourceManager.GetObject("material_editor_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_mode_16 {
            get {
                object obj = ResourceManager.GetObject("material_mode_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_mode_24 {
            get {
                object obj = ResourceManager.GetObject("material_mode_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_mode_32 {
            get {
                object obj = ResourceManager.GetObject("material_mode_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        internal static string Mode_Materials {
            get {
                return ResourceManager.GetString("Mode_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Unassigned -.
        /// </summary>
        internal static string Name_Unassigned {
            get {
                return ResourceManager.GetString("Name_Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slate_16 {
            get {
                object obj = ResourceManager.GetObject("slate_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slate_new_view_16 {
            get {
                object obj = ResourceManager.GetObject("slate_new_view_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Material editor slot items -.
        /// </summary>
        internal static string Str_EditMaterialItems {
            get {
                return ResourceManager.GetString("Str_EditMaterialItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Str_Objects {
            get {
                return ResourceManager.GetString("Str_Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Maps.
        /// </summary>
        internal static string Str_TextureMaps {
            get {
                return ResourceManager.GetString("Str_TextureMaps", resourceCulture);
            }
        }
    }
}
