//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJanssen.Outliner.Modes.Layer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PJanssen.Outliner.Modes.Layer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to layer.
        /// </summary>
        internal static string Command_AddToLayer {
            get {
                return ResourceManager.GetString("Command_AddToLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new layer.
        /// </summary>
        internal static string Command_CreateNewLayer {
            get {
                return ResourceManager.GetString("Command_CreateNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as current layer.
        /// </summary>
        internal static string Command_SetCurrentLayer {
            get {
                return ResourceManager.GetString("Command_SetCurrentLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unparent layer.
        /// </summary>
        internal static string Command_UnlinkLayer {
            get {
                return ResourceManager.GetString("Command_UnlinkLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new layer.
        /// </summary>
        internal static string Context_CreateEmptyLayer {
            get {
                return ResourceManager.GetString("Context_CreateEmptyLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selection to new layer.
        /// </summary>
        internal static string Context_CreateLayerFromSelection {
            get {
                return ResourceManager.GetString("Context_CreateLayerFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set active layer.
        /// </summary>
        internal static string Context_SetCurrentLayer {
            get {
                return ResourceManager.GetString("Context_SetCurrentLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_16 {
            get {
                object obj = ResourceManager.GetObject("layer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_mode_16 {
            get {
                object obj = ResourceManager.GetObject("layer_mode_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_mode_24 {
            get {
                object obj = ResourceManager.GetObject("layer_mode_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_mode_32 {
            get {
                object obj = ResourceManager.GetObject("layer_mode_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string Mode_Layer {
            get {
                return ResourceManager.GetString("Mode_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_layer_16 {
            get {
                object obj = ResourceManager.GetObject("new_layer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap set_active_layer_16 {
            get {
                object obj = ResourceManager.GetObject("set_active_layer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Add To Layer Items -.
        /// </summary>
        internal static string Str_AddToLayerItems {
            get {
                return ResourceManager.GetString("Str_AddToLayerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string Str_ILayer {
            get {
                return ResourceManager.GetString("Str_ILayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        internal static string Str_LayerDefault {
            get {
                return ResourceManager.GetString("Str_LayerDefault", resourceCulture);
            }
        }
    }
}
